[project]
name = "pytorchstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tensorboard>=2.20.0",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
]
